server:
  port: "8081"
backend:
  url: "ws://175.27.250.177:8080"
  call_type: "webrtc"
audio:
  codec: "g722"
asr:
  provider: "tencent"
  language: "zh-CN"
  sample_rate: 16000
  app_id: ""
  secret_id: ""
  secret_key: ""
  endpoint: "asr.tencentcloudapi.com"
  model_type: "16k_zh"
tts:
  provider: "tencent"
  sample_rate: 16000
  speaker: "601008"
  speed: 1
  volume: 10
  emotion: "jieshuo"
  app_id: ""
  secret_id: ""
  secret_key: ""
  codec: "pcm"
  endpoint: "tts.tencentcloudapi.com"
llm:
  api_key: ""
  model: "qwen-turbo"
  url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  system_prompt: "You are a helpful assistant. Provide concise responses. Use 'hangup' tool when the conversation is complete."
  siliconflow:
    api_key: ""
    url: "https://api.siliconflow.cn/v1/chat/completions"
    model: "THUDM/GLM-Z1-9B-0414"
    system_prompt: "You are a helpful assistant. Provide concise responses. Use 'hangup' tool when the conversation is complete. 如果我说使用联网搜索那你就使用这个search online这个工具，如果我说生成图片那你就使用generate image这个工具.please use Chinese to replay!! 铭记使用中文回答！！"
big_model:
  # https://bigmodel.cn/dev/howuse/introduction 注册账号获取API Key
  search_api_url: "https://open.bigmodel.cn/api/paas/v4/assistant"
  search_api_key: ""
  search_api_model: "glm-4v-flash"
vad:
  model: "silero"
  endpoint: ""
  secret_key: ""
call:
  break_on_vad: false
  with_sip: false
  record: false
  caller: ""
  callee: ""
webhook:
  addr: ""
  prefix: "/webhook"
eou:
  type: ""
  endpoint: ""
database:
  dsn: "{}:{}@tcp({}:3306)/VoicePBX?charset=utf8mb4&parseTime=True&loc=Local"